### ISSUE TITLE
Remove the `create` method from the CRUDState algebra

### ISSUE THREAD

**Issue by FrancoAra** [lambdaone-io/kratia-centralized#20]
* if the store generates the ID then a sub class can be implemented
* rename the `createPick` method to `create`

**Comment by kolov** [comment]
What is the motivation behind this proposal? If the store generates ID, then e.g. `Collector.createBallotBox` can't simple emit an event because there is no ID for BallotBoxCreatedEvent. What will be an event-store approach for this situation?

**Comment by FrancoAra** [comment]
The motivation is that: the id generation is ONLY used on the create method, the user of the CRUDStore may or may not need `create` with ID generation, if he doesn't need it then the user will use `createPick`, if the user does need it and the ID is generated on the server side then he can use `createPick` using the `UniqueGen` algebra outside the CRUDStore, if the ID is generated on the database side then `createPick` can be used with any id, it is going to be ignored any way. So in all cases `create` is not really needed. If the 3rd case becomes important then we can create an algebra that extends CRUDStore and adds `create` with the requirement of an UniqueGen in the implementation
