### ISSUE TITLE
Write the first Collector algebra with simple interpreter

### ISSUE THREAD

**Issue by FrancoAra** [lambdaone-io/kratia-centralized#7]
(Note: everything under the kratia root package is deprecated, but might be used as a reference or to salvage code)

* Under the package lambdaone.kratia.collector write a tagless final interface that matches the basic model
* Includes the model for `Vote`, `Ballot`, `BallotBox` and `ProofOfVote` 
* Make a simple interpreter that implements it using a `lambdaone.toolbox.State`
* Make simple interfaces for missing required code that belongs to other issues

**Comment by kolov** [comment]
Work in progress in the collector branch
